### ISSUE TITLE
Deepseek V3.2 MLA Support on gfx906

### ISSUE THREAD

**Issue by ai-infos** [nlzy/vllm-gfx906#57]
I tried on a single node of 16 MI50 32GB (512 GB VRAM in total) on vllm-gfx906 v0.11.2 with this command: 

```code
FLASH_ATTENTION_TRITON_AMD_ENABLE="TRUE" VLLM_ATTENTION_BACKEND="TRITON_MLA" NCCL_P2P_DISABLE=1 VLLM_MLA_DISABLE=0 VLLM_USE_TRITON_AWQ=1 VLLM_LOGGING_LEVEL=DEBUG NCCL_DEBUG=INFO vllm serve ~/llm/models/DeepSeek-V3.2-Speciale-AWQ \
    --served-model-name DeepSeek-V3.2-Speciale-AWQ \
    --reasoning-parser deepseek_r1 \
    --enable-expert-parallel \
    --chat-template ~/llm/models/DeepSeek-V3.2-Speciale-AWQ/chat_template.jinja \
    --tensor-parallel-size 8 --pipeline-parallel-size 2 --max-model-len 132000 --gpu-memory-utilization 0.95 \
    --swap-space 0 2>&1 | tee log.txt
```

(quant used: https://huggingface.co/QuantTrio/DeepSeek-V3.2-Speciale-AWQ)

But got garbage output after 2 prompts (the beggining of the last response is pretty consistent but the end is out of topic).

To make it load, I have to:
- add flash-attn v2.8.3 module with amd triton backend (from official repo https://github.com/Dao-AILab/flash-attention/tree/v2.8.3 )
- update deepseek_v2.py with "is_v32 = False" and skip the load of the indexer weights (as sparse is not yet supported with triton rocm):
```code
                        # ========================================================
                        # [FIX] DeepSeek-V3.2 Patch: Ignore Missing Indexer Weights
                        # ========================================================
                        if name not in params_dict:
                            if "indexer" in name:
                                # Silently skip the indexer weights if the model
                                # config has disabled the indexer module.
                                continue
                        # ========================================================
                        param = params_dict[name] 
```

So I guess, where it fails might be at the flash-attn module part (using flash_attn_varlen_func and attn_fwd(...) from flash_attn/flash_attn_triton_amd/fwd_prefill.py) & at the vllm/attention/ops/triton_decode_attention.py part both not adapted for gfx906.

NB: I could make it run with good outputs Deepseek v3.1 (https://huggingface.co/cpatonn/DeepSeek-V3.1-GPTQ-4bit ) but without MLA and with low kv cache (max-model-len 10000) thanks to the ops/triton_unified_attention.py being adapted for gfx906.

**Comment by ai-infos** [comment]
1st attempt to make Deespeek work on GFX906 :  https://github.com/nlzy/vllm-gfx906/pull/62 

We can say that this issue is fixed by this PR with sparse and MTP enabled (but still need improvements)
