### ISSUE TITLE
[Bug]: HIP error: invalid device function

### ISSUE THREAD

**Issue by weizihua** [nlzy/vllm-gfx906#6]
### Your current environment

<details>

```text
INFO 05-15 18:58:43 [model_runner.py:1108] Starting to load model ./QwQ-32B-GGUF/qwq-32b-q4_k_m.gguf...
Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.
WARNING 05-15 18:58:58 [rocm.py:285] Model architecture 'Qwen2ForCausalLM' is partially supported by ROCm: Sliding window attention (SWA) is not yet supported in Triton flash attention. For half-precision SWA support, please use CK flash attention by setting `VLLM_USE_TRITON_FLASH_ATTN=0`
ERROR 05-15 18:58:58 [engine.py:448] HIP error: invalid device function
ERROR 05-15 18:58:58 [engine.py:448] Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
ERROR 05-15 18:58:58 [engine.py:448] Traceback (most recent call last):
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
ERROR 05-15 18:58:58 [engine.py:448]     engine = MQLLMEngine.from_vllm_config(
ERROR 05-15 18:58:58 [engine.py:448]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 128, in from_vllm_config
ERROR 05-15 18:58:58 [engine.py:448]     return cls(
ERROR 05-15 18:58:58 [engine.py:448]            ^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 82, in __init__
ERROR 05-15 18:58:58 [engine.py:448]     self.engine = LLMEngine(*args, **kwargs)
ERROR 05-15 18:58:58 [engine.py:448]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 275, in __init__
ERROR 05-15 18:58:58 [engine.py:448]     self.model_executor = executor_class(vllm_config=vllm_config)
ERROR 05-15 18:58:58 [engine.py:448]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 52, in __init__
ERROR 05-15 18:58:58 [engine.py:448]     self._init_executor()
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
ERROR 05-15 18:58:58 [engine.py:448]     self.collective_rpc("load_model")
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
ERROR 05-15 18:58:58 [engine.py:448]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 05-15 18:58:58 [engine.py:448]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/utils.py", line 2456, in run_method
ERROR 05-15 18:58:58 [engine.py:448]     return func(*args, **kwargs)
ERROR 05-15 18:58:58 [engine.py:448]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/worker/worker.py", line 203, in load_model
ERROR 05-15 18:58:58 [engine.py:448]     self.model_runner.load_model()
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1111, in load_model
ERROR 05-15 18:58:58 [engine.py:448]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 05-15 18:58:58 [engine.py:448]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
ERROR 05-15 18:58:58 [engine.py:448]     return loader.load_model(vllm_config=vllm_config)
ERROR 05-15 18:58:58 [engine.py:448]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 1407, in load_model
ERROR 05-15 18:58:58 [engine.py:448]     model = _initialize_model(vllm_config=vllm_config)
ERROR 05-15 18:58:58 [engine.py:448]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 133, in _initialize_model
ERROR 05-15 18:58:58 [engine.py:448]     return model_class(vllm_config=vllm_config, prefix=prefix)
ERROR 05-15 18:58:58 [engine.py:448]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 436, in __init__
ERROR 05-15 18:58:58 [engine.py:448]     self.model = Qwen2Model(vllm_config=vllm_config,
ERROR 05-15 18:58:58 [engine.py:448]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/compilation/decorators.py", line 151, in __init__
ERROR 05-15 18:58:58 [engine.py:448]     old_init(self, vllm_config=vllm_config, prefix=prefix, **kwargs)
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 305, in __init__
ERROR 05-15 18:58:58 [engine.py:448]     self.start_layer, self.end_layer, self.layers = make_layers(
ERROR 05-15 18:58:58 [engine.py:448]                                                     ^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 609, in make_layers
ERROR 05-15 18:58:58 [engine.py:448]     [PPMissingLayer() for _ in range(start_layer)] + [
ERROR 05-15 18:58:58 [engine.py:448]                                                      ^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 610, in <listcomp>
ERROR 05-15 18:58:58 [engine.py:448]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
ERROR 05-15 18:58:58 [engine.py:448]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 307, in <lambda>
ERROR 05-15 18:58:58 [engine.py:448]     lambda prefix: decoder_layer_type(config=config,
ERROR 05-15 18:58:58 [engine.py:448]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 205, in __init__
ERROR 05-15 18:58:58 [engine.py:448]     self.self_attn = Qwen2Attention(
ERROR 05-15 18:58:58 [engine.py:448]                      ^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 152, in __init__
ERROR 05-15 18:58:58 [engine.py:448]     self.rotary_emb = get_rope(
ERROR 05-15 18:58:58 [engine.py:448]                       ^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/layers/rotary_embedding.py", line 1500, in get_rope
ERROR 05-15 18:58:58 [engine.py:448]     rotary_emb = RotaryEmbedding(head_size, rotary_dim, max_position, base,
ERROR 05-15 18:58:58 [engine.py:448]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/layers/rotary_embedding.py", line 109, in __init__
ERROR 05-15 18:58:58 [engine.py:448]     cache = self._compute_cos_sin_cache()
ERROR 05-15 18:58:58 [engine.py:448]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/layers/rotary_embedding.py", line 126, in _compute_cos_sin_cache
ERROR 05-15 18:58:58 [engine.py:448]     inv_freq = self._compute_inv_freq(self.base)
ERROR 05-15 18:58:58 [engine.py:448]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/layers/rotary_embedding.py", line 120, in _compute_inv_freq
ERROR 05-15 18:58:58 [engine.py:448]     inv_freq = 1.0 / (base**(torch.arange(
ERROR 05-15 18:58:58 [engine.py:448]                              ^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448]   File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/torch/utils/_device.py", line 104, in __torch_function__
ERROR 05-15 18:58:58 [engine.py:448]     return func(*args, **kwargs)
ERROR 05-15 18:58:58 [engine.py:448]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 05-15 18:58:58 [engine.py:448] RuntimeError: HIP error: invalid device function
ERROR 05-15 18:58:58 [engine.py:448] Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
ERROR 05-15 18:58:58 [engine.py:448] 
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 450, in run_mp_engine
    raise e
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
    engine = MQLLMEngine.from_vllm_config(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 128, in from_vllm_config
    return cls(
           ^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 82, in __init__
    self.engine = LLMEngine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 275, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 52, in __init__
    self._init_executor()
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
    self.collective_rpc("load_model")
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/utils.py", line 2456, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/worker/worker.py", line 203, in load_model
    self.model_runner.load_model()
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1111, in load_model
    self.model = get_model(vllm_config=self.vllm_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
    return loader.load_model(vllm_config=vllm_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 1407, in load_model
    model = _initialize_model(vllm_config=vllm_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 133, in _initialize_model
    return model_class(vllm_config=vllm_config, prefix=prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 436, in __init__
    self.model = Qwen2Model(vllm_config=vllm_config,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/compilation/decorators.py", line 151, in __init__
    old_init(self, vllm_config=vllm_config, prefix=prefix, **kwargs)
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 305, in __init__
    self.start_layer, self.end_layer, self.layers = make_layers(
                                                    ^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 609, in make_layers
    [PPMissingLayer() for _ in range(start_layer)] + [
                                                     ^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 610, in <listcomp>
    maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 307, in <lambda>
    lambda prefix: decoder_layer_type(config=config,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 205, in __init__
    self.self_attn = Qwen2Attention(
                     ^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 152, in __init__
    self.rotary_emb = get_rope(
                      ^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/layers/rotary_embedding.py", line 1500, in get_rope
    rotary_emb = RotaryEmbedding(head_size, rotary_dim, max_position, base,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/layers/rotary_embedding.py", line 109, in __init__
    cache = self._compute_cos_sin_cache()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/layers/rotary_embedding.py", line 126, in _compute_cos_sin_cache
    inv_freq = self._compute_inv_freq(self.base)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/model_executor/layers/rotary_embedding.py", line 120, in _compute_inv_freq
    inv_freq = 1.0 / (base**(torch.arange(
                             ^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/torch/utils/_device.py", line 104, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: invalid device function
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

[rank0]:[W515 18:58:59.257566893 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Traceback (most recent call last):
  File "/home/zerone/miniconda3/envs/gfx906/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/entrypoints/cli/main.py", line 53, in main
    args.dispatch_function(args)
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/entrypoints/cli/serve.py", line 27, in cmd
    uvloop.run(run_server(args))
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/uvloop/__init__.py", line 105, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 1078, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 146, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerone/miniconda3/envs/gfx906/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 269, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.
```

</details>

### 🐛 Describe the bug

NCCL_DEBUG=INFO AMD_SERIALIZE_KERNEL=1 HSA_ENABLE_SDMA=0 ROCM_PATH=/opt/rocm PYTHONPATH=/home/zerone/code/nlzy/triton-gfx906/python HIP_VISIBLE_DEVICES=0,1 TORCH_BLAS_PREFER_HIPBLASLT=0 PYTORCH_ROCM_ARCH=gfx906   vllm serve ./QwQ-32B-GGUF/qwq-32b-q4_k_m.gguf --host 0.0.0.0 --port 8080 --tensor-parallel-size 2 --quantization awq --dtype float16 --block-size 32 --max-num-seqs 64 --max-model-len 10960 --tensor-parallel-size 1 --enable-auto-tool-choice --tool-call-parser hermes --api-key abcd123456

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by chernming** [comment]
建立虚拟环境 添加
export PATH=$PATH:/opt/rocm/bin
export ROCM_PATH=/opt/rocm
export ROCM_HOME=/opt/rocm
export VLLM_TARGET_DEVICE="rocm"
export PYTORCH_ROCM_ARCH="gfx906"
export HSA_OVERRIDE_GFX_VERSION=9.0.6

编译前确保存在cmath 和 C++ 标准头文件
sudo apt update
sudo apt install build-essential g++-11 libstdc++-11-dev
sudo apt update
sudo apt install -y libstdc++-11-dev libc++-dev libc++abi-dev
git 带版本号
git clone -b v3.3.0+gfx906 https://github.com/nlzy/triton-gfx906.git
git clone -b v0.8.5+gfx906 https://github.com/nlzy/vllm-gfx906.git
再解决一些编译工具软连接 环境变量 就好了
